### ISSUE TITLE
Implement a secrets guardian

### ISSUE THREAD

**Issue by delucca** [budproj/business#120]
## 🧐 The problem

Since we're an open-source company, any contributor could accidentally commit a secret in our git repository. When that happens, we need to act quickly to prevent any bad actor from exploiting that vulnerability.

## 💡 What solution do I want

We could implement [Gitguardian](https://www.gitguardian.com/pricing) or any other tool that can monitor our secrets.

## 😰 What have I tried to do already

Nothing.

## 🍪 Further details

@victorperin suggested the following Github action:
```yaml
name: GitGuardian scan

on: [push, pull_request]

jobs:
  scanning:
    name: GitGuardian scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all history so multiple commits can be scanned
      - name: GitGuardian scan
        uses: GitGuardian/gg-shield-action@master
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
```

Also, after creating that structure, we should consider implementing it on our other repositories as well.
